apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sosmed-chart.fullname" . }}
  labels:
    {{- include "sosmed-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
   dbhost: {{ .Values.secret.dbhost }}
   dbuser: {{ .Values.secret.dbuser }}
   dbpassword: {{ .Values.secret.dbpassword }}
   dbname: {{ .Values.secret.dbname }}
